name: "Setup"
description: "Setup"

inputs:
  mix-env:
    description: "Mix env"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: "1.19.4"
        otp-version: "28.3"

    # - name: Restore dependencies cache
    #   uses: actions/cache@v4
    #   with:
    #     path: deps
    #     key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    #     restore-keys: ${{ runner.os }}-mix-

    # - name: Restore build cache
    #   uses: actions/cache@v4
    #   with:
    #     path: _build
    #     key: ${{ runner.os }}-build-elixir
    #     restore-keys: ${{ runner.os }}-build-elixir

    - name: build
      run: |
        mix deps.get --only
        mix compile --warnings-as-errors
      shell: bash
